# Generated by Django 5.0.4 on 2024-04-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_alter_habitacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='habitaciones.categoria'),
        ),
    ]
